CREATE DATABASE IF NOT EXISTS pharmapack_qms CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE pharmapack_qms;
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS serialized_units,capa_actions,deviations,audit_trails,electronic_signatures,qa_reviews,reconciliations,inspection_defects,defects,aql_inspections,aql_plans,production_entries,production_runs,material_verifications,line_clearance_checks,line_clearances,packaging_orders,batches,packaging_lines,equipment,material_lots,materials,user_roles,users,roles,products;
SET FOREIGN_KEY_CHECKS=1;

CREATE TABLE roles(id BIGINT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(50) NOT NULL UNIQUE,description VARCHAR(255));
CREATE TABLE users(id BIGINT AUTO_INCREMENT PRIMARY KEY,username VARCHAR(100) NOT NULL UNIQUE,password_hash VARCHAR(255) NOT NULL,full_name VARCHAR(150) NOT NULL,email VARCHAR(180),status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE user_roles(user_id BIGINT NOT NULL,role_id BIGINT NOT NULL,PRIMARY KEY(user_id,role_id),FOREIGN KEY(user_id) REFERENCES users(id),FOREIGN KEY(role_id) REFERENCES roles(id));
CREATE TABLE products(id BIGINT AUTO_INCREMENT PRIMARY KEY,product_code VARCHAR(80) NOT NULL UNIQUE,product_name VARCHAR(200) NOT NULL,strength VARCHAR(100),dosage_form VARCHAR(100),pack_size VARCHAR(100),status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE materials(id BIGINT AUTO_INCREMENT PRIMARY KEY,material_code VARCHAR(80) NOT NULL UNIQUE,material_name VARCHAR(200) NOT NULL,material_type VARCHAR(80) NOT NULL,uom VARCHAR(30) NOT NULL,status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE');
CREATE TABLE material_lots(id BIGINT AUTO_INCREMENT PRIMARY KEY,material_id BIGINT NOT NULL,lot_number VARCHAR(100) NOT NULL,supplier VARCHAR(200),quantity DECIMAL(15,3) NOT NULL DEFAULT 0,expiry_date DATE,status VARCHAR(30) DEFAULT 'AVAILABLE',UNIQUE(material_id,lot_number),FOREIGN KEY(material_id) REFERENCES materials(id));
CREATE TABLE equipment(id BIGINT AUTO_INCREMENT PRIMARY KEY,equipment_code VARCHAR(80) NOT NULL UNIQUE,equipment_name VARCHAR(200) NOT NULL,equipment_type VARCHAR(100),status VARCHAR(30) DEFAULT 'AVAILABLE',calibration_due_date DATE);
CREATE TABLE packaging_lines(id BIGINT AUTO_INCREMENT PRIMARY KEY,line_code VARCHAR(80) NOT NULL UNIQUE,line_name VARCHAR(150) NOT NULL,location VARCHAR(150),status VARCHAR(30) DEFAULT 'AVAILABLE');
CREATE TABLE batches(id BIGINT AUTO_INCREMENT PRIMARY KEY,batch_number VARCHAR(100) NOT NULL UNIQUE,product_id BIGINT NOT NULL,lot_size DECIMAL(15,3) NOT NULL,batch_status VARCHAR(50) DEFAULT 'CREATED',manufacturing_date DATE,expiry_date DATE,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(product_id) REFERENCES products(id),CHECK(lot_size>0),CHECK(expiry_date IS NULL OR manufacturing_date IS NULL OR expiry_date>=manufacturing_date));
CREATE TABLE packaging_orders(id BIGINT AUTO_INCREMENT PRIMARY KEY,batch_id BIGINT NOT NULL,line_id BIGINT NOT NULL,planned_quantity DECIMAL(15,3) NOT NULL,scheduled_start DATETIME,scheduled_end DATETIME,status VARCHAR(40) DEFAULT 'PLANNED',FOREIGN KEY(batch_id) REFERENCES batches(id),FOREIGN KEY(line_id) REFERENCES packaging_lines(id));
CREATE TABLE line_clearances(id BIGINT AUTO_INCREMENT PRIMARY KEY,batch_id BIGINT NOT NULL,line_id BIGINT NOT NULL,performed_by BIGINT,performed_at DATETIME DEFAULT CURRENT_TIMESTAMP,approved_by BIGINT,approved_at DATETIME,status VARCHAR(40) DEFAULT 'PENDING',comments VARCHAR(1000),FOREIGN KEY(batch_id) REFERENCES batches(id),FOREIGN KEY(line_id) REFERENCES packaging_lines(id),FOREIGN KEY(performed_by) REFERENCES users(id),FOREIGN KEY(approved_by) REFERENCES users(id));
CREATE TABLE line_clearance_checks(id BIGINT AUTO_INCREMENT PRIMARY KEY,line_clearance_id BIGINT NOT NULL,check_code VARCHAR(80) NOT NULL,check_description VARCHAR(500) NOT NULL,result VARCHAR(30) DEFAULT 'NOT_CHECKED',evidence_reference VARCHAR(255),remarks VARCHAR(1000),FOREIGN KEY(line_clearance_id) REFERENCES line_clearances(id));
CREATE TABLE material_verifications(id BIGINT AUTO_INCREMENT PRIMARY KEY,batch_id BIGINT NOT NULL,material_lot_id BIGINT NOT NULL,verified_quantity DECIMAL(15,3) NOT NULL,verified_by BIGINT,verified_at DATETIME DEFAULT CURRENT_TIMESTAMP,status VARCHAR(40) DEFAULT 'PENDING',remarks VARCHAR(1000),FOREIGN KEY(batch_id) REFERENCES batches(id),FOREIGN KEY(material_lot_id) REFERENCES material_lots(id),FOREIGN KEY(verified_by) REFERENCES users(id));
CREATE TABLE production_runs(id BIGINT AUTO_INCREMENT PRIMARY KEY,batch_id BIGINT NOT NULL,line_id BIGINT NOT NULL,equipment_id BIGINT,started_at DATETIME,ended_at DATETIME,status VARCHAR(40) DEFAULT 'PLANNED',FOREIGN KEY(batch_id) REFERENCES batches(id),FOREIGN KEY(line_id) REFERENCES packaging_lines(id),FOREIGN KEY(equipment_id) REFERENCES equipment(id));
CREATE TABLE production_entries(id BIGINT AUTO_INCREMENT PRIMARY KEY,production_run_id BIGINT NOT NULL,entry_time DATETIME DEFAULT CURRENT_TIMESTAMP,quantity_produced DECIMAL(15,3) DEFAULT 0,quantity_good DECIMAL(15,3) DEFAULT 0,quantity_reject DECIMAL(15,3) DEFAULT 0,operator_id BIGINT,remarks VARCHAR(1000),FOREIGN KEY(production_run_id) REFERENCES production_runs(id),FOREIGN KEY(operator_id) REFERENCES users(id));
CREATE TABLE aql_plans(id BIGINT AUTO_INCREMENT PRIMARY KEY,plan_code VARCHAR(80) NOT NULL UNIQUE,inspection_level VARCHAR(30) NOT NULL,aql_value DECIMAL(8,3) NOT NULL,sample_size INT NOT NULL,acceptance_number INT NOT NULL,rejection_number INT NOT NULL,description VARCHAR(500));
CREATE TABLE aql_inspections(id BIGINT AUTO_INCREMENT PRIMARY KEY,batch_id BIGINT NOT NULL,aql_plan_id BIGINT NOT NULL,inspector_id BIGINT,inspection_time DATETIME DEFAULT CURRENT_TIMESTAMP,sample_size INT NOT NULL,defects_found INT DEFAULT 0,result VARCHAR(40) DEFAULT 'PENDING',remarks VARCHAR(1000),FOREIGN KEY(batch_id) REFERENCES batches(id),FOREIGN KEY(aql_plan_id) REFERENCES aql_plans(id),FOREIGN KEY(inspector_id) REFERENCES users(id));
CREATE TABLE defects(id BIGINT AUTO_INCREMENT PRIMARY KEY,defect_code VARCHAR(80) NOT NULL UNIQUE,defect_name VARCHAR(200) NOT NULL,defect_class VARCHAR(40) NOT NULL,description VARCHAR(500),status VARCHAR(30) DEFAULT 'ACTIVE');
CREATE TABLE inspection_defects(id BIGINT AUTO_INCREMENT PRIMARY KEY,aql_inspection_id BIGINT NOT NULL,defect_id BIGINT NOT NULL,quantity INT DEFAULT 1,remarks VARCHAR(1000),FOREIGN KEY(aql_inspection_id) REFERENCES aql_inspections(id),FOREIGN KEY(defect_id) REFERENCES defects(id));
CREATE TABLE reconciliations(id BIGINT AUTO_INCREMENT PRIMARY KEY,batch_id BIGINT NOT NULL UNIQUE,starting_quantity DECIMAL(15,3) NOT NULL,good_quantity DECIMAL(15,3) DEFAULT 0,reject_quantity DECIMAL(15,3) DEFAULT 0,unused_quantity DECIMAL(15,3) DEFAULT 0,reconciled_quantity DECIMAL(15,3) DEFAULT 0,variance DECIMAL(15,3) DEFAULT 0,status VARCHAR(50) DEFAULT 'INVESTIGATION_REQUIRED',calculated_at DATETIME DEFAULT CURRENT_TIMESTAMP,calculated_by BIGINT,remarks VARCHAR(1000),FOREIGN KEY(batch_id) REFERENCES batches(id),FOREIGN KEY(calculated_by) REFERENCES users(id));
CREATE TABLE qa_reviews(id BIGINT AUTO_INCREMENT PRIMARY KEY,batch_id BIGINT NOT NULL,reviewer_id BIGINT,review_type VARCHAR(80) NOT NULL,decision VARCHAR(50) DEFAULT 'PENDING',review_date DATETIME DEFAULT CURRENT_TIMESTAMP,comments VARCHAR(2000),FOREIGN KEY(batch_id) REFERENCES batches(id),FOREIGN KEY(reviewer_id) REFERENCES users(id));
CREATE TABLE electronic_signatures(id BIGINT AUTO_INCREMENT PRIMARY KEY,user_id BIGINT NOT NULL,entity_name VARCHAR(100) NOT NULL,entity_id VARCHAR(100) NOT NULL,action_type VARCHAR(100) NOT NULL,signed_at DATETIME DEFAULT CURRENT_TIMESTAMP,signature_reason VARCHAR(500),FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE audit_trails(id BIGINT AUTO_INCREMENT PRIMARY KEY,username VARCHAR(100) NOT NULL,action_type VARCHAR(100) NOT NULL,entity_name VARCHAR(100),entity_id VARCHAR(100),field_name VARCHAR(100),old_value TEXT,new_value TEXT,created_at DATETIME DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE deviations(id BIGINT AUTO_INCREMENT PRIMARY KEY,deviation_number VARCHAR(100) NOT NULL UNIQUE,batch_id BIGINT,title VARCHAR(250) NOT NULL,description TEXT NOT NULL,severity VARCHAR(40) NOT NULL,status VARCHAR(50) DEFAULT 'OPEN',opened_by BIGINT,opened_at DATETIME DEFAULT CURRENT_TIMESTAMP,closed_at DATETIME,FOREIGN KEY(batch_id) REFERENCES batches(id),FOREIGN KEY(opened_by) REFERENCES users(id));
CREATE TABLE capa_actions(id BIGINT AUTO_INCREMENT PRIMARY KEY,deviation_id BIGINT NOT NULL,action_type VARCHAR(40) NOT NULL,action_description TEXT NOT NULL,owner_id BIGINT,due_date DATE,completed_date DATE,status VARCHAR(40) DEFAULT 'OPEN',effectiveness_result VARCHAR(1000),FOREIGN KEY(deviation_id) REFERENCES deviations(id),FOREIGN KEY(owner_id) REFERENCES users(id));
-- Phase 3D: unit-level serialization + hierarchical aggregation (UNIT under CASE under
-- PALLET), in the spirit of the DSCSA / EU-FMD "serialization and aggregation" capability
-- that global pharma packaging providers publicly advertise (see docs/PHASE3D_*).
CREATE TABLE serialized_units(id BIGINT AUTO_INCREMENT PRIMARY KEY,batch_id BIGINT NOT NULL,serial_number VARCHAR(120) NOT NULL UNIQUE,gtin VARCHAR(20),aggregation_level VARCHAR(20) NOT NULL DEFAULT 'UNIT',parent_id BIGINT,status VARCHAR(30) NOT NULL DEFAULT 'CREATED',commissioned_at DATETIME NULL,commissioned_by BIGINT NULL,FOREIGN KEY(batch_id) REFERENCES batches(id),FOREIGN KEY(parent_id) REFERENCES serialized_units(id),FOREIGN KEY(commissioned_by) REFERENCES users(id));
CREATE TABLE serialization_events(id BIGINT AUTO_INCREMENT PRIMARY KEY,serialized_unit_id BIGINT NOT NULL,event_type VARCHAR(40) NOT NULL,event_result VARCHAR(40),reason_code VARCHAR(80),operator_id BIGINT,details VARCHAR(1000),event_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(serialized_unit_id) REFERENCES serialized_units(id),FOREIGN KEY(operator_id) REFERENCES users(id));
CREATE TABLE vision_results(id BIGINT AUTO_INCREMENT PRIMARY KEY,serialized_unit_id BIGINT NOT NULL,expected_barcode VARCHAR(120),actual_barcode VARCHAR(120),expected_lot VARCHAR(80),actual_lot VARCHAR(80),expected_expiry VARCHAR(40),actual_expiry VARCHAR(40),barcode_pass BOOLEAN NOT NULL,lot_pass BOOLEAN NOT NULL,expiry_pass BOOLEAN NOT NULL,decision VARCHAR(10) NOT NULL,device_name VARCHAR(100),checked_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(serialized_unit_id) REFERENCES serialized_units(id));
CREATE INDEX idx_batches_product ON batches(product_id);
CREATE INDEX idx_audit_entity ON audit_trails(entity_name,entity_id);
CREATE INDEX idx_serial_batch ON serialized_units(batch_id);
CREATE INDEX idx_serial_parent ON serialized_units(parent_id);
