package com.pharmapack.qms.production;
import com.pharmapack.qms.batch.*; import com.pharmapack.qms.master.*; import org.springframework.http.*; import org.springframework.web.bind.annotation.*; import java.math.*; import java.time.*; import java.util.*;
@RestController @RequestMapping("/api/production") public class ProductionController { final ProductionRunRepository rr; final ProductionEntryRepository er; final BatchRepository br; final LineRepository lr; final EquipmentRepository eqr; public ProductionController(ProductionRunRepository r,ProductionEntryRepository e,BatchRepository b,LineRepository l,EquipmentRepository eq){rr=r;er=e;br=b;lr=l;eqr=eq;}
 @GetMapping("/runs") public List<ProductionRunResponse> runs(){return rr.findAllWithRefs().stream().map(this::dto).toList();}
 public record RunCreate(Long batchId,Long lineId,Long equipmentId){} @PostMapping("/runs") @ResponseStatus(HttpStatus.CREATED) public ProductionRunResponse run(@RequestBody RunCreate x){Batch b=br.findById(x.batchId()).orElseThrow(()->new IllegalArgumentException("Batch not found")); if(x.lineId()==null)throw new IllegalArgumentException("lineId is required"); PackagingLine l=lr.findById(x.lineId()).orElseThrow(()->new IllegalArgumentException("Packaging line not found")); Equipment eq=x.equipmentId()==null?null:eqr.findById(x.equipmentId()).orElseThrow(()->new IllegalArgumentException("Equipment not found")); ProductionRun saved=rr.save(ProductionRun.builder().batch(b).line(l).equipment(eq).startedAt(LocalDateTime.now()).status("IN_PROGRESS").build()); return dto(rr.findById(saved.getId()).orElseThrow());}
 public record EntryCreate(Long runId,BigDecimal produced,BigDecimal good,BigDecimal reject,Long operatorId,String remarks){}
 @PostMapping("/entries") @ResponseStatus(HttpStatus.CREATED) public ProductionEntryResponse entry(@RequestBody EntryCreate x){ if(x.produced()==null||x.good()==null||x.reject()==null||x.produced().signum()<0||x.good().signum()<0||x.reject().signum()<0)throw new IllegalArgumentException("Production quantities must be non-negative"); if(x.good().add(x.reject()).compareTo(x.produced())>0)throw new IllegalArgumentException("Good + Reject cannot exceed Produced"); ProductionRun r=rr.findById(x.runId()).orElseThrow(()->new IllegalArgumentException("Production run not found")); ProductionEntry e=new ProductionEntry();e.setProductionRun(r);e.setEntryTime(LocalDateTime.now());e.setQuantityProduced(x.produced());e.setQuantityGood(x.good());e.setQuantityReject(x.reject());e.setOperatorId(x.operatorId());e.setRemarks(x.remarks());ProductionEntry saved=er.save(e);return entryDto(er.findById(saved.getId()).orElseThrow());}
 @GetMapping("/runs/{id}/entries") public List<ProductionEntryResponse> entries(@PathVariable Long id){return er.findByProductionRunIdOrderByEntryTimeAsc(id).stream().map(this::entryDto).toList();}
 ProductionRunResponse dto(ProductionRun r){var b=r.getBatch();var l=r.getLine();var eq=r.getEquipment();return new ProductionRunResponse(r.getId(),b==null?null:b.getId(),b==null?null:b.getBatchNumber(),b==null?null:b.getProduct().getProductCode(),b==null?null:b.getProduct().getProductName(),l==null?null:l.getId(),l==null?null:l.getLineCode(),l==null?null:l.getLineName(),eq==null?null:eq.getId(),eq==null?null:eq.getEquipmentCode(),eq==null?null:eq.getEquipmentName(),r.getStartedAt(),r.getEndedAt(),r.getStatus());}
 ProductionEntryResponse entryDto(ProductionEntry e){var r=e.getProductionRun();var b=r==null?null:r.getBatch();return new ProductionEntryResponse(e.getId(),r==null?null:r.getId(),b==null?null:b.getId(),b==null?null:b.getBatchNumber(),e.getEntryTime(),e.getQuantityProduced(),e.getQuantityGood(),e.getQuantityReject(),e.getOperatorId(),e.getRemarks());}
}
