package com.pharmapack.qms.batch;
import com.pharmapack.qms.audit.AuditTrailService; import com.pharmapack.qms.product.*; import org.springframework.stereotype.Service; import java.math.*; import java.time.*; import java.util.*;
@Service public class BatchService { final BatchRepository br; final ProductRepository pr; final AuditTrailService at; public BatchService(BatchRepository b,ProductRepository p,AuditTrailService a){br=b;pr=p;at=a;}
 public List<BatchResponse> list(){return br.findAllWithProduct().stream().map(this::dto).toList();} public BatchResponse get(Long id){return dto(br.findWithProduct(id).orElseThrow(()->new IllegalArgumentException("Batch not found: "+id)));}
 public BatchResponse create(String n,Long pid,BigDecimal lot,LocalDate m,LocalDate e){if(n==null||n.isBlank())throw new IllegalArgumentException("Batch number is required");if(lot==null||lot.signum()<=0)throw new IllegalArgumentException("Lot size must be greater than zero");if(e!=null&&m!=null&&e.isBefore(m))throw new IllegalArgumentException("Expiry date cannot precede manufacturing date");if(br.existsByBatchNumber(n))throw new IllegalArgumentException("Duplicate batch number");
  Product p=pr.findById(pid).orElseThrow(()->new IllegalArgumentException("Product not found: "+pid)); Batch b=br.save(Batch.builder().batchNumber(n).product(p).lotSize(lot).manufacturingDate(m).expiryDate(e).build()); at.log("CREATE","Batch",b.getId(),"batchNumber",null,b.getBatchNumber()); return get(b.getId()); }
 public BatchResponse status(Long id,BatchStatus st){Batch b=br.findWithProduct(id).orElseThrow(()->new IllegalArgumentException("Batch not found: "+id)); BatchStatus old=b.getBatchStatus(); b.setBatchStatus(st);br.save(b);at.log("STATUS_CHANGE","Batch",id,"batchStatus",old,st);return dto(b);}
 BatchResponse dto(Batch b){return new BatchResponse(b.getId(),b.getBatchNumber(),b.getProduct().getId(),b.getProduct().getProductCode(),b.getProduct().getProductName(),b.getLotSize(),b.getBatchStatus(),b.getManufacturingDate(),b.getExpiryDate());}
}
